// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_INFO        LogLevel = 1
	LogLevel_LOG_LEVEL_SUCCESS     LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 5
	LogLevel_LOG_LEVEL_PLAIN       LogLevel = 6
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_INFO",
		2: "LOG_LEVEL_SUCCESS",
		3: "LOG_LEVEL_WARNING",
		4: "LOG_LEVEL_ERROR",
		5: "LOG_LEVEL_DEBUG",
		6: "LOG_LEVEL_PLAIN",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_INFO":        1,
		"LOG_LEVEL_SUCCESS":     2,
		"LOG_LEVEL_WARNING":     3,
		"LOG_LEVEL_ERROR":       4,
		"LOG_LEVEL_DEBUG":       5,
		"LOG_LEVEL_PLAIN":       6,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_plugin_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Commands      []*CommandSpec         `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetManifestResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetManifestResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetManifestResponse) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

type CommandSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Short         string                 `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"`
	Long          string                 `protobuf:"bytes,3,opt,name=long,proto3" json:"long,omitempty"`
	Subcommands   []*CommandSpec         `protobuf:"bytes,4,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CommandSpec) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *CommandSpec) GetSubcommands() []*CommandSpec {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Debug         bool                   `protobuf:"varint,5,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *ExecuteRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

type GetAuthContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthContextRequest) Reset() {
	*x = GetAuthContextRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthContextRequest) ProtoMessage() {}

func (x *GetAuthContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthContextRequest.ProtoReflect.Descriptor instead.
func (*GetAuthContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

type GetAuthContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OrgId         uint64                 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgName       string                 `protobuf:"bytes,3,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	ApiBaseUrl    string                 `protobuf:"bytes,6,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthContextResponse) Reset() {
	*x = GetAuthContextResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthContextResponse) ProtoMessage() {}

func (x *GetAuthContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthContextResponse.ProtoReflect.Descriptor instead.
func (*GetAuthContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthContextResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetAuthContextResponse) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *GetAuthContextResponse) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *GetAuthContextResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAuthContextResponse) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GetAuthContextResponse) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type APIRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRequestRequest) Reset() {
	*x = APIRequestRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequestRequest) ProtoMessage() {}

func (x *APIRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequestRequest.ProtoReflect.Descriptor instead.
func (*APIRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *APIRequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIRequestRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *APIRequestRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type APIRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRequestResponse) Reset() {
	*x = APIRequestResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequestResponse) ProtoMessage() {}

func (x *APIRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequestResponse.ProtoReflect.Descriptor instead.
func (*APIRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *APIRequestResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIRequestResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiBaseUrl    string                 `protobuf:"bytes,1,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	DerpUrl       string                 `protobuf:"bytes,2,opt,name=derp_url,json=derpUrl,proto3" json:"derp_url,omitempty"`
	HomeDir       string                 `protobuf:"bytes,3,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *GetConfigResponse) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

func (x *GetConfigResponse) GetDerpUrl() string {
	if x != nil {
		return x.DerpUrl
	}
	return ""
}

func (x *GetConfigResponse) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *GetConfigResponse) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=plugin.v1.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *LogRequest) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

type PromptInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	IsSecret      bool                   `protobuf:"varint,2,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptInputRequest) Reset() {
	*x = PromptInputRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptInputRequest) ProtoMessage() {}

func (x *PromptInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptInputRequest.ProtoReflect.Descriptor instead.
func (*PromptInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PromptInputRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PromptInputRequest) GetIsSecret() bool {
	if x != nil {
		return x.IsSecret
	}
	return false
}

type PromptInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptInputResponse) Reset() {
	*x = PromptInputResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptInputResponse) ProtoMessage() {}

func (x *PromptInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptInputResponse.ProtoReflect.Descriptor instead.
func (*PromptInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *PromptInputResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PromptConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptConfirmRequest) Reset() {
	*x = PromptConfirmRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptConfirmRequest) ProtoMessage() {}

func (x *PromptConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptConfirmRequest.ProtoReflect.Descriptor instead.
func (*PromptConfirmRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *PromptConfirmRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PromptConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptConfirmResponse) Reset() {
	*x = PromptConfirmResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptConfirmResponse) ProtoMessage() {}

func (x *PromptConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptConfirmResponse.ProtoReflect.Descriptor instead.
func (*PromptConfirmResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *PromptConfirmResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\tplugin.v1\"\x14\n" +
	"\x12GetManifestRequest\"\x99\x01\n" +
	"\x13GetManifestResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\bcommands\x18\x04 \x03(\v2\x16.plugin.v1.CommandSpecR\bcommands\"\x85\x01\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05short\x18\x02 \x01(\tR\x05short\x12\x12\n" +
	"\x04long\x18\x03 \x01(\tR\x04long\x128\n" +
	"\vsubcommands\x18\x04 \x03(\v2\x16.plugin.v1.CommandSpecR\vsubcommands\"\xee\x01\n" +
	"\x0eExecuteRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x124\n" +
	"\x03env\x18\x02 \x03(\v2\".plugin.v1.ExecuteRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\x12\x14\n" +
	"\x05debug\x18\x05 \x01(\bR\x05debug\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0fExecuteResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\"\x17\n" +
	"\x15GetAuthContextRequest\"\xba\x01\n" +
	"\x16GetAuthContextResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\x04R\x05orgId\x12\x19\n" +
	"\borg_name\x18\x03 \x01(\tR\aorgName\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12 \n" +
	"\fapi_base_url\x18\x06 \x01(\tR\n" +
	"apiBaseUrl\"[\n" +
	"\x11APIRequestRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"I\n" +
	"\x12APIRequestResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\"\x12\n" +
	"\x10GetConfigRequest\"\x90\x01\n" +
	"\x11GetConfigResponse\x12 \n" +
	"\fapi_base_url\x18\x01 \x01(\tR\n" +
	"apiBaseUrl\x12\x19\n" +
	"\bderp_url\x18\x02 \x01(\tR\aderpUrl\x12\x19\n" +
	"\bhome_dir\x18\x03 \x01(\tR\ahomeDir\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\"Q\n" +
	"\n" +
	"LogRequest\x12)\n" +
	"\x05level\x18\x01 \x01(\x0e2\x13.plugin.v1.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\r\n" +
	"\vLogResponse\"G\n" +
	"\x12PromptInputRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\tis_secret\x18\x02 \x01(\bR\bisSecret\"+\n" +
	"\x13PromptInputResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\",\n" +
	"\x14PromptConfirmRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"5\n" +
	"\x15PromptConfirmResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed*\xa6\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x01\x12\x15\n" +
	"\x11LOG_LEVEL_SUCCESS\x10\x02\x12\x15\n" +
	"\x11LOG_LEVEL_WARNING\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x05\x12\x13\n" +
	"\x0fLOG_LEVEL_PLAIN\x10\x062\x9f\x01\n" +
	"\rPluginService\x12L\n" +
	"\vGetManifest\x12\x1d.plugin.v1.GetManifestRequest\x1a\x1e.plugin.v1.GetManifestResponse\x12@\n" +
	"\aExecute\x12\x19.plugin.v1.ExecuteRequest\x1a\x1a.plugin.v1.ExecuteResponse2\xcf\x03\n" +
	"\vHostService\x12U\n" +
	"\x0eGetAuthContext\x12 .plugin.v1.GetAuthContextRequest\x1a!.plugin.v1.GetAuthContextResponse\x12I\n" +
	"\n" +
	"APIRequest\x12\x1c.plugin.v1.APIRequestRequest\x1a\x1d.plugin.v1.APIRequestResponse\x12F\n" +
	"\tGetConfig\x12\x1b.plugin.v1.GetConfigRequest\x1a\x1c.plugin.v1.GetConfigResponse\x124\n" +
	"\x03Log\x12\x15.plugin.v1.LogRequest\x1a\x16.plugin.v1.LogResponse\x12L\n" +
	"\vPromptInput\x12\x1d.plugin.v1.PromptInputRequest\x1a\x1e.plugin.v1.PromptInputResponse\x12R\n" +
	"\rPromptConfirm\x12\x1f.plugin.v1.PromptConfirmRequest\x1a .plugin.v1.PromptConfirmResponseB8Z6github.com/warp-run/prysm-cli/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(LogLevel)(0),                  // 0: plugin.v1.LogLevel
	(*GetManifestRequest)(nil),     // 1: plugin.v1.GetManifestRequest
	(*GetManifestResponse)(nil),    // 2: plugin.v1.GetManifestResponse
	(*CommandSpec)(nil),            // 3: plugin.v1.CommandSpec
	(*ExecuteRequest)(nil),         // 4: plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),        // 5: plugin.v1.ExecuteResponse
	(*GetAuthContextRequest)(nil),  // 6: plugin.v1.GetAuthContextRequest
	(*GetAuthContextResponse)(nil), // 7: plugin.v1.GetAuthContextResponse
	(*APIRequestRequest)(nil),      // 8: plugin.v1.APIRequestRequest
	(*APIRequestResponse)(nil),     // 9: plugin.v1.APIRequestResponse
	(*GetConfigRequest)(nil),       // 10: plugin.v1.GetConfigRequest
	(*GetConfigResponse)(nil),      // 11: plugin.v1.GetConfigResponse
	(*LogRequest)(nil),             // 12: plugin.v1.LogRequest
	(*LogResponse)(nil),            // 13: plugin.v1.LogResponse
	(*PromptInputRequest)(nil),     // 14: plugin.v1.PromptInputRequest
	(*PromptInputResponse)(nil),    // 15: plugin.v1.PromptInputResponse
	(*PromptConfirmRequest)(nil),   // 16: plugin.v1.PromptConfirmRequest
	(*PromptConfirmResponse)(nil),  // 17: plugin.v1.PromptConfirmResponse
	nil,                            // 18: plugin.v1.ExecuteRequest.EnvEntry
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: plugin.v1.GetManifestResponse.commands:type_name -> plugin.v1.CommandSpec
	3,  // 1: plugin.v1.CommandSpec.subcommands:type_name -> plugin.v1.CommandSpec
	18, // 2: plugin.v1.ExecuteRequest.env:type_name -> plugin.v1.ExecuteRequest.EnvEntry
	0,  // 3: plugin.v1.LogRequest.level:type_name -> plugin.v1.LogLevel
	1,  // 4: plugin.v1.PluginService.GetManifest:input_type -> plugin.v1.GetManifestRequest
	4,  // 5: plugin.v1.PluginService.Execute:input_type -> plugin.v1.ExecuteRequest
	6,  // 6: plugin.v1.HostService.GetAuthContext:input_type -> plugin.v1.GetAuthContextRequest
	8,  // 7: plugin.v1.HostService.APIRequest:input_type -> plugin.v1.APIRequestRequest
	10, // 8: plugin.v1.HostService.GetConfig:input_type -> plugin.v1.GetConfigRequest
	12, // 9: plugin.v1.HostService.Log:input_type -> plugin.v1.LogRequest
	14, // 10: plugin.v1.HostService.PromptInput:input_type -> plugin.v1.PromptInputRequest
	16, // 11: plugin.v1.HostService.PromptConfirm:input_type -> plugin.v1.PromptConfirmRequest
	2,  // 12: plugin.v1.PluginService.GetManifest:output_type -> plugin.v1.GetManifestResponse
	5,  // 13: plugin.v1.PluginService.Execute:output_type -> plugin.v1.ExecuteResponse
	7,  // 14: plugin.v1.HostService.GetAuthContext:output_type -> plugin.v1.GetAuthContextResponse
	9,  // 15: plugin.v1.HostService.APIRequest:output_type -> plugin.v1.APIRequestResponse
	11, // 16: plugin.v1.HostService.GetConfig:output_type -> plugin.v1.GetConfigResponse
	13, // 17: plugin.v1.HostService.Log:output_type -> plugin.v1.LogResponse
	15, // 18: plugin.v1.HostService.PromptInput:output_type -> plugin.v1.PromptInputResponse
	17, // 19: plugin.v1.HostService.PromptConfirm:output_type -> plugin.v1.PromptConfirmResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
