{{- if .Values.configSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.configSecret.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
