#!/usr/bin/env bash
#
# Build release artifacts for prysm-cli and publish to the prysm-cli repo.
# Usage: scripts/release_artifacts.sh <version>

set -euo pipefail

REPO="${RELEASE_REPO:-prysmsh/cli}"

usage() {
  cat <<EOF
Usage: $(basename "$0") <version>

Examples:
  $(basename "$0") 1.4.0
  $(basename "$0") v1.4.0

Publishes to: github.com/${REPO}
EOF
  exit 1
}

[[ $# -ge 1 ]] || usage

RAW_VERSION="$1"
VERSION="${RAW_VERSION#v}"

if [[ -z "$VERSION" ]]; then
  echo "error: unable to determine version from input '$RAW_VERSION'" >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST_ROOT="${ROOT_DIR}/dist/releases/${VERSION}"
rm -rf "$DIST_ROOT"
mkdir -p "$DIST_ROOT"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command '$1' not found in PATH" >&2
    exit 1
  fi
}

require_cmd go
require_cmd tar
require_cmd gzip
require_cmd zip

export PATH="$(go env GOPATH)/bin:${PATH}"

if ! command -v nfpm >/dev/null 2>&1; then
  echo "nfpm not found – installing..."
  go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.37.1
fi

file_sha256() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$path" | awk '{print $1}'
  else
    openssl dgst -sha256 "$path" | awk '{print $2}'
  fi
}

package_artifacts() {
  local package="$1"
  local install_name="$2"
  local binary_path="$3"
  local os="$4"
  local arch="$5"
  local description="$6"

  local binary_abs
  binary_abs="$(realpath "$binary_path")"
  local format="binary"
  if [[ "$binary_abs" == *.exe ]]; then
    format="exe"
  fi

  case "$os" in
    linux)
      local tar_tmp
      tar_tmp="$(mktemp -d)"
      cp "$binary_abs" "$tar_tmp/$install_name"
      chmod 0755 "$tar_tmp/$install_name"
      local tarball="${DIST_ROOT}/${package}-${VERSION}-linux-${arch}.tar.gz"
      tar -C "$tar_tmp" -czf "$tarball" "$install_name"
      rm -rf "$tar_tmp"

      local nfpm_cfg
      nfpm_cfg="$(mktemp)"
      cat <<EOF >"$nfpm_cfg"
name: ${package}
arch: ${arch}
platform: linux
version: ${VERSION}
section: utils
priority: optional
maintainer: Prysm Engineering <engineering@prysm.sh>
description: ${description}
license: MIT
contents:
  - src: ${binary_abs}
    dst: /usr/local/bin/${install_name}
    file_info:
      mode: 0755
EOF

      local deb_target="${DIST_ROOT}/${package}_${VERSION}_${arch}.deb"
      local rpm_arch="$arch"
      case "$arch" in
        amd64) rpm_arch="x86_64" ;;
        arm64) rpm_arch="aarch64" ;;
      esac
      local rpm_target="${DIST_ROOT}/${package}-${VERSION}-1.${rpm_arch}.rpm"
      nfpm pkg --packager deb --config "$nfpm_cfg" --target "$deb_target"
      nfpm pkg --packager rpm --config "$nfpm_cfg" --target "$rpm_target"
      rm -f "$nfpm_cfg"
      ;;
    darwin)
      local tar_tmp
      tar_tmp="$(mktemp -d)"
      cp "$binary_abs" "$tar_tmp/$install_name"
      chmod 0755 "$tar_tmp/$install_name"
      local tarball="${DIST_ROOT}/${package}-${VERSION}-darwin-${arch}.tar.gz"
      tar -C "$tar_tmp" -czf "$tarball" "$install_name"
      rm -rf "$tar_tmp"
      ;;
    windows)
      local zip_tmp
      zip_tmp="$(mktemp -d)"
      local exe_name="${install_name}.exe"
      cp "$binary_abs" "$zip_tmp/$exe_name"
      chmod 0755 "$zip_tmp/$exe_name"
      local zip_target="${DIST_ROOT}/${package}-${VERSION}-windows-${arch}.zip"
      (cd "$zip_tmp" && zip -q "$zip_target" "$exe_name")
      rm -rf "$zip_tmp"
      ;;
    *)
      echo "error: unsupported OS '${os}'" >&2
      exit 1
      ;;
  esac
}

generate_release_notes() {
  local notes_path="${DIST_ROOT}/RELEASE_NOTES.md"
  local generated_at
  generated_at="$(date -u +"%Y-%m-%d %H:%M:%SZ")"

  {
    printf "# Prysm CLI Release v%s\n\n" "$VERSION"
    printf "_Generated %s_\n\n" "$generated_at"
    printf "## Artifacts\n\n"
    printf "| Filename | SHA256 |\n"
    printf "| --- | --- |\n"
  } >"$notes_path"

  while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    filename="$(basename "$f")"
    sha="$(file_sha256 "$f")"
    printf "| %s | %s |\n" "$filename" "$sha" >>"$notes_path"
  done < <(find "$DIST_ROOT" -maxdepth 1 -type f ! -name "RELEASE_NOTES.md" -print | sort)

  printf '\nGenerated by scripts/release_artifacts.sh.\n' >>"$notes_path"
  echo "$notes_path"
}

publish_github_release() {
  local notes_path="$1"

  if [[ -n "${SKIP_GH_RELEASE:-}" ]]; then
    echo "Skipping GitHub release publication (SKIP_GH_RELEASE set)."
    return
  fi

  if [[ -z "$notes_path" || ! -f "$notes_path" ]]; then
    echo "warning: release notes path '$notes_path' not found" >&2
    return
  fi

  if ! command -v gh >/dev/null 2>&1; then
    echo "warning: gh CLI not found – skipping GitHub release" >&2
    return
  fi

  if ! gh auth status >/dev/null 2>&1; then
    echo "warning: gh CLI not authenticated – skipping GitHub release" >&2
    return
  fi

  local release_assets
  release_assets="$(find "$DIST_ROOT" -maxdepth 1 -type f ! -name "RELEASE_NOTES.md" -print | sort)"
  if [[ -z "$release_assets" ]]; then
    echo "warning: no release assets found" >&2
    return
  fi

  local tag="v${VERSION}"
  local title="Prysm CLI ${tag}"

  if gh release view "$tag" --repo "$REPO" >/dev/null 2>&1; then
    echo "Updating existing GitHub release ${tag}"
    gh release edit "$tag" --repo "$REPO" --notes-file "$notes_path"
    while IFS= read -r asset; do
      [[ -z "$asset" ]] || gh release upload "$tag" "$asset" --repo "$REPO" --clobber
    done <<<"$release_assets"
  else
    echo "Creating GitHub release ${tag} in ${REPO}"
    gh release create "$tag" --repo "$REPO" --title "$title" --notes-file "$notes_path"
    while IFS= read -r asset; do
      [[ -z "$asset" ]] || gh release upload "$tag" "$asset" --repo "$REPO"
    done <<<"$release_assets"
  fi
}

echo "Building prysm-cli release artifacts for version ${VERSION}"
echo "Publishing to: github.com/${REPO}"

package="prysm-cli"
install_name="prysm"
description="Prysm zero-trust infrastructure CLI"

targets=(
  "linux amd64"
  "linux arm64"
  "darwin amd64"
  "darwin arm64"
  "windows amd64"
)

pushd "$ROOT_DIR" >/dev/null
for combo in "${targets[@]}"; do
  os="${combo%% *}"
  arch="${combo##* }"
  output="${DIST_ROOT}/${package}-${VERSION}-${os}-${arch}"
  extension=""
  [[ "$os" == "windows" ]] && extension=".exe"

  env CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" \
    go build -trimpath -ldflags "-s -w -X github.com/warp-run/prysm-cli/internal/cmd.version=${VERSION}" \
    -o "${output}${extension}" ./cmd/prysm

  chmod 0755 "${output}${extension}"
  package_artifacts "$package" "$install_name" "${output}${extension}" "$os" "$arch" "$description"
done
popd >/dev/null

notes_file="$(generate_release_notes)"
publish_github_release "$notes_file"

echo
echo "Artifacts written to: $DIST_ROOT"
find "$DIST_ROOT" -maxdepth 1 -type f -print | sort
